# Project 3

##### Team member: Zhihong Zhang.

## Part 1: Introduction ##

The dataset of this project is based on chess tournament results where the information has some structure. The goal is to make an organized csv file.

#### The setting up of the project

In [1]:
#starting point:import the library and data set
import numpy as np
import pandas as pd
import re

tournamentinfo ='https://raw.githubusercontent.com/steinszzh/DAV-5400/master/project3/tournamentinfo.txt'
tournament = pd.read_csv(tournamentinfo,index_col=0)
# data set check - make sure data was read in as expected
tournament.head()

Empty DataFrame
Columns: []
Index: [ Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| ,  Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | , -----------------------------------------------------------------------------------------,     1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|,    ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |]

By default setting, due to its bad formitting, we can tell that another way of processing text should be used. Firstly, to read whole file and have a nice overview of the data. I start with reading text function.

In [2]:
#read whole txt
filepath = 'tournamentinfo.txt'
with open(filepath) as fp:
   line = fp.readline()
   cnt = 1
   while line:
       print("Line {}: {}".format(cnt, line.strip()))
       line = fp.readline()
       cnt += 1

Line 1: -----------------------------------------------------------------------------------------
Line 2: Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round|
Line 3: Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  |
Line 4: -----------------------------------------------------------------------------------------
Line 5: 1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|
Line 6: ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |
Line 7: -----------------------------------------------------------------------------------------
Line 8: 2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|
Line 9: MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |
Line 10: -----------------------------------------------------------------------------------------
Line 11: 3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|
Line 12: MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |
Line 13: -----------------------------------------------------------------------------------------
Line 14: 4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|
Line 15: MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |
Line 16: -----------------------------------------------------------------------------------------
Line 17: 5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|
Line 18: MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |
Line 19: -----------------------------------------------------------------------------------------
Line 20: 6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|
Line 21: OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |
Line 22: -----------------------------------------------------------------------------------------
Line 23: 7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|
Line 24: MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |
Line 25: -----------------------------------------------------------------------------------------
Line 26: 8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|
Line 27: MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |
Line 28: -----------------------------------------------------------------------------------------
Line 29: 9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|
Line 30: ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |
Line 31: -----------------------------------------------------------------------------------------
Line 32: 10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|
Line 33: MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |
Line 34: -----------------------------------------------------------------------------------------
Line 35: 11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|
Line 36: MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |
Line 37: -----------------------------------------------------------------------------------------
Line 38: 12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|
Line 39: MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |
Line 40: -----------------------------------------------------------------------------------------
Line 41: 13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|
Line 42: MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |
Line 43: -----------------------------------------------------------------------------------------
Line 44: 14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|
Line 45: MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |
Line 46: -----------------------------------------------------------------------------------------
Line 47: 15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|
Line 48: MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |
Line 49: -----------------------------------------------------------------------------------------
Line 50: 16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |
Line 51: MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |
Line 52: -----------------------------------------------------------------------------------------
Line 53: 17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|
Line 54: MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |
Line 55: -----------------------------------------------------------------------------------------
Line 56: 18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|
Line 57: MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |
Line 58: -----------------------------------------------------------------------------------------
Line 59: 19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|
Line 60: MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |
Line 61: -----------------------------------------------------------------------------------------
Line 62: 20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|
Line 63: MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |
Line 64: -----------------------------------------------------------------------------------------
Line 65: 21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|
Line 66: ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |
Line 67: -----------------------------------------------------------------------------------------
Line 68: 22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|
Line 69: MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |
Line 70: -----------------------------------------------------------------------------------------
Line 71: 23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|
Line 72: ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |
Line 73: -----------------------------------------------------------------------------------------
Line 74: 24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|
Line 75: MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |
Line 76: -----------------------------------------------------------------------------------------
Line 77: 25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|
Line 78: MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |
Line 79: -----------------------------------------------------------------------------------------
Line 80: 26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|
Line 81: ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |
Line 82: -----------------------------------------------------------------------------------------
Line 83: 27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |
Line 84: MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |
Line 85: -----------------------------------------------------------------------------------------
Line 86: 28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|
Line 87: MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |
Line 88: -----------------------------------------------------------------------------------------
Line 89: 29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |
Line 90: MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |
Line 91: -----------------------------------------------------------------------------------------
Line 92: 30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|
Line 93: ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |
Line 94: -----------------------------------------------------------------------------------------
Line 95: 31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|
Line 96: MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |
Line 97: -----------------------------------------------------------------------------------------
Line 98: 32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|
Line 99: ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |
Line 100: -----------------------------------------------------------------------------------------
Line 101: 33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|
Line 102: MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |
Line 103: -----------------------------------------------------------------------------------------
Line 104: 34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|
Line 105: MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |
Line 106: -----------------------------------------------------------------------------------------
Line 107: 35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|
Line 108: MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |
Line 109: -----------------------------------------------------------------------------------------
Line 110: 36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|
Line 111: MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |
Line 112: -----------------------------------------------------------------------------------------
Line 113: 37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|
Line 114: MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |
Line 115: -----------------------------------------------------------------------------------------
Line 116: 38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|
Line 117: MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |
Line 118: -----------------------------------------------------------------------------------------
Line 119: 39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|
Line 120: MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |
Line 121: -----------------------------------------------------------------------------------------
Line 122: 40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|
Line 123: MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |
Line 124: -----------------------------------------------------------------------------------------
Line 125: 41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |
Line 126: MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |
Line 127: -----------------------------------------------------------------------------------------
Line 128: 42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|
Line 129: MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |
Line 130: -----------------------------------------------------------------------------------------
Line 131: 43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|
Line 132: MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |
Line 133: -----------------------------------------------------------------------------------------
Line 134: 44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|
Line 135: MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |
Line 136: -----------------------------------------------------------------------------------------
Line 137: 45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|
Line 138: MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |
Line 139: -----------------------------------------------------------------------------------------
Line 140: 46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|
Line 141: MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |
Line 142: -----------------------------------------------------------------------------------------
Line 143: 47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|
Line 144: MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |
Line 145: -----------------------------------------------------------------------------------------
Line 146: 48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|
Line 147: MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |
Line 148: -----------------------------------------------------------------------------------------
Line 149: 49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |
Line 150: MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |
Line 151: -----------------------------------------------------------------------------------------
Line 152: 50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|
Line 153: MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |
Line 154: -----------------------------------------------------------------------------------------
Line 155: 51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|
Line 156: MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |
Line 157: -----------------------------------------------------------------------------------------
Line 158: 52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|
Line 159: MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |
Line 160: -----------------------------------------------------------------------------------------
Line 161: 53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |
Line 162: MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |
Line 163: -----------------------------------------------------------------------------------------
Line 164: 54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|
Line 165: MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |
Line 166: -----------------------------------------------------------------------------------------
Line 167: 55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|
Line 168: MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |
Line 169: -----------------------------------------------------------------------------------------
Line 170: 56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|
Line 171: MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |
Line 172: -----------------------------------------------------------------------------------------
Line 173: 57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |
Line 174: MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |
Line 175: -----------------------------------------------------------------------------------------
Line 176: 58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|
Line 177: MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |
Line 178: -----------------------------------------------------------------------------------------
Line 179: 59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|
Line 180: MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |
Line 181: -----------------------------------------------------------------------------------------
Line 182: 60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |
Line 183: MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |
Line 184: -----------------------------------------------------------------------------------------
Line 185: 61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|
Line 186: ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |
Line 187: -----------------------------------------------------------------------------------------
Line 188: 62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |
Line 189: MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |
Line 190: -----------------------------------------------------------------------------------------
Line 191: 63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |
Line 192: MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |
Line 193: -----------------------------------------------------------------------------------------
Line 194: 64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|
Line 195: MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |
Line 196: -----------------------------------------------------------------------------------------

Firstly, check the whole data set. There are total of 64 players. And I decide to only keep these information of each player(pair name, player id, two rating score, total points, each round and his/her opponent number. ) The pattern also showed that every four line (beginning with dash line and ending with dash line) will be another player. Based on this , I decided to start with a list.

## Part 2: Data cleaning

In [3]:
#import extra package
import csv

In [4]:

#makng a list to reorganize and clean data

with open('tournamentinfo.txt', 'r') as f:
  reader = csv.reader(f)
  my_list = list(reader)

print(my_list)

[['-----------------------------------------------------------------------------------------'], [' Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| '], [' Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | '], ['-----------------------------------------------------------------------------------------'], ['    1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|'], ['   ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['    2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|'], ['   MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['    3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|'], ['   MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['    4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|'], ['   MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |'], ['-----------------------------------------------------------------------------------------'], ['    5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|'], ['   MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['    6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|'], ['   OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['    7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|'], ['   MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['    8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|'], ['   MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['    9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|'], ['   ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|'], ['   MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|'], ['   MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|'], ['   MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|'], ['   MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|'], ['   MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|'], ['   MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |'], ['   MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |'], ['-----------------------------------------------------------------------------------------'], ['   17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|'], ['   MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|'], ['   MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|'], ['   MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|'], ['   MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|'], ['   ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|'], ['   MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|'], ['   ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|'], ['   MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|'], ['   MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|'], ['   ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |'], ['   MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |'], ['-----------------------------------------------------------------------------------------'], ['   28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|'], ['   MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |'], ['   MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |'], ['-----------------------------------------------------------------------------------------'], ['   30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|'], ['   ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|'], ['   MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|'], ['   ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|'], ['   MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|'], ['   MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|'], ['   MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|'], ['   MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|'], ['   MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|'], ['   MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|'], ['   MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|'], ['   MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |'], ['   MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |'], ['-----------------------------------------------------------------------------------------'], ['   42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|'], ['   MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|'], ['   MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|'], ['   MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|'], ['   MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|'], ['   MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|'], ['   MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|'], ['   MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |'], ['   MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |'], ['-----------------------------------------------------------------------------------------'], ['   50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|'], ['   MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|'], ['   MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|'], ['   MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |'], ['   MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |'], ['-----------------------------------------------------------------------------------------'], ['   54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|'], ['   MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|'], ['   MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|'], ['   MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |'], ['-----------------------------------------------------------------------------------------'], ['   57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |'], ['   MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |'], ['-----------------------------------------------------------------------------------------'], ['   58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|'], ['   MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |'], ['-----------------------------------------------------------------------------------------'], ['   59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|'], ['   MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |'], ['   MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |'], ['-----------------------------------------------------------------------------------------'], ['   61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|'], ['   ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |'], ['-----------------------------------------------------------------------------------------'], ['   62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |'], ['   MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |'], ['-----------------------------------------------------------------------------------------'], ['   63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |'], ['   MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |'], ['-----------------------------------------------------------------------------------------'], ['   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|'], ['   MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |'], ['-----------------------------------------------------------------------------------------']]

In [5]:
#Test couple of data points
my_list[4]
my_list[7]
#check the length of whole list
length=len(my_list)
length
#Got 196 list and it matched earlier 196 lines.
#check whether it is last player on line 193. And it is verified.
my_list[193]

['   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|']

By analyzing the pattern, we can tell that starting from fourth line, every three list is a new player 's total points and round data.Also, next line(list) is corresponding location,ID and rating data. In addition, previous read text data is verified here. So a general algorithm can be generated.

In [18]:
#Firstly, create player with total points, and round only. 
#Based on analysis, we can tell that the distance between two player data is two 

#using np arange to make spaced value. In this case, since we know the stop number of the line is 196.
row_num = np.arange(1,196,3)
step = 0
#create an empty player only list
player_only = []

#using for loop to get player only data
for i in my_list:
    if(step in row_num):
        player_only.append(i)
    step = step+1
#get player only data
player_only

[[' Pair | Player Name                     |Total|Round|Round|Round|Round|Round|Round|Round| '],
 ['    1 | GARY HUA                        |6.0  |W  39|W  21|W  18|W  14|W   7|D  12|D   4|'],
 ['    2 | DAKSHESH DARURI                 |6.0  |W  63|W  58|L   4|W  17|W  16|W  20|W   7|'],
 ['    3 | ADITYA BAJAJ                    |6.0  |L   8|W  61|W  25|W  21|W  11|W  13|W  12|'],
 ['    4 | PATRICK H SCHILLING             |5.5  |W  23|D  28|W   2|W  26|D   5|W  19|D   1|'],
 ['    5 | HANSHI ZUO                      |5.5  |W  45|W  37|D  12|D  13|D   4|W  14|W  17|'],
 ['    6 | HANSEN SONG                     |5.0  |W  34|D  29|L  11|W  35|D  10|W  27|W  21|'],
 ['    7 | GARY DEE SWATHELL               |5.0  |W  57|W  46|W  13|W  11|L   1|W   9|L   2|'],
 ['    8 | EZEKIEL HOUGHTON                |5.0  |W   3|W  32|L  14|L   9|W  47|W  28|W  19|'],
 ['    9 | STEFANO LEE                     |5.0  |W  25|L  18|W  59|W   8|W  26|L   7|W  20|'],
 ['   10 | ANVIT RAO                       |5.0  |D  16|L  19|W  55|W  31|D   6|W  25|W  18|'],
 ['   11 | CAMERON WILLIAM MC LEMAN        |4.5  |D  38|W  56|W   6|L   7|L   3|W  34|W  26|'],
 ['   12 | KENNETH J TACK                  |4.5  |W  42|W  33|D   5|W  38|H    |D   1|L   3|'],
 ['   13 | TORRANCE HENRY JR               |4.5  |W  36|W  27|L   7|D   5|W  33|L   3|W  32|'],
 ['   14 | BRADLEY SHAW                    |4.5  |W  54|W  44|W   8|L   1|D  27|L   5|W  31|'],
 ['   15 | ZACHARY JAMES HOUGHTON          |4.5  |D  19|L  16|W  30|L  22|W  54|W  33|W  38|'],
 ['   16 | MIKE NIKITIN                    |4.0  |D  10|W  15|H    |W  39|L   2|W  36|U    |'],
 ['   17 | RONALD GRZEGORCZYK              |4.0  |W  48|W  41|L  26|L   2|W  23|W  22|L   5|'],
 ['   18 | DAVID SUNDEEN                   |4.0  |W  47|W   9|L   1|W  32|L  19|W  38|L  10|'],
 ['   19 | DIPANKAR ROY                    |4.0  |D  15|W  10|W  52|D  28|W  18|L   4|L   8|'],
 ['   20 | JASON ZHENG                     |4.0  |L  40|W  49|W  23|W  41|W  28|L   2|L   9|'],
 ['   21 | DINH DANG BUI                   |4.0  |W  43|L   1|W  47|L   3|W  40|W  39|L   6|'],
 ['   22 | EUGENE L MCCLURE                |4.0  |W  64|D  52|L  28|W  15|H    |L  17|W  40|'],
 ['   23 | ALAN BUI                        |4.0  |L   4|W  43|L  20|W  58|L  17|W  37|W  46|'],
 ['   24 | MICHAEL R ALDRICH               |4.0  |L  28|L  47|W  43|L  25|W  60|W  44|W  39|'],
 ['   25 | LOREN SCHWIEBERT                |3.5  |L   9|W  53|L   3|W  24|D  34|L  10|W  47|'],
 ['   26 | MAX ZHU                         |3.5  |W  49|W  40|W  17|L   4|L   9|D  32|L  11|'],
 ['   27 | GAURAV GIDWANI                  |3.5  |W  51|L  13|W  46|W  37|D  14|L   6|U    |'],
 ['   28 | SOFIA ADINA STANESCU-BELLU      |3.5  |W  24|D   4|W  22|D  19|L  20|L   8|D  36|'],
 ['   29 | CHIEDOZIE OKORIE                |3.5  |W  50|D   6|L  38|L  34|W  52|W  48|U    |'],
 ['   30 | GEORGE AVERY JONES              |3.5  |L  52|D  64|L  15|W  55|L  31|W  61|W  50|'],
 ['   31 | RISHI SHETTY                    |3.5  |L  58|D  55|W  64|L  10|W  30|W  50|L  14|'],
 ['   32 | JOSHUA PHILIP MATHEWS           |3.5  |W  61|L   8|W  44|L  18|W  51|D  26|L  13|'],
 ['   33 | JADE GE                         |3.5  |W  60|L  12|W  50|D  36|L  13|L  15|W  51|'],
 ['   34 | MICHAEL JEFFERY THOMAS          |3.5  |L   6|W  60|L  37|W  29|D  25|L  11|W  52|'],
 ['   35 | JOSHUA DAVID LEE                |3.5  |L  46|L  38|W  56|L   6|W  57|D  52|W  48|'],
 ['   36 | SIDDHARTH JHA                   |3.5  |L  13|W  57|W  51|D  33|H    |L  16|D  28|'],
 ['   37 | AMIYATOSH PWNANANDAM            |3.5  |B    |L   5|W  34|L  27|H    |L  23|W  61|'],
 ['   38 | BRIAN LIU                       |3.0  |D  11|W  35|W  29|L  12|H    |L  18|L  15|'],
 ['   39 | JOEL R HENDON                   |3.0  |L   1|W  54|W  40|L  16|W  44|L  21|L  24|'],
 ['   40 | FOREST ZHANG                    |3.0  |W  20|L  26|L  39|W  59|L  21|W  56|L  22|'],
 ['   41 | KYLE WILLIAM MURPHY             |3.0  |W  59|L  17|W  58|L  20|X    |U    |U    |'],
 ['   42 | JARED GE                        |3.0  |L  12|L  50|L  57|D  60|D  61|W  64|W  56|'],
 ['   43 | ROBERT GLEN VASEY               |3.0  |L  21|L  23|L  24|W  63|W  59|L  46|W  55|'],
 ['   44 | JUSTIN D SCHILLING              |3.0  |B    |L  14|L  32|W  53|L  39|L  24|W  59|'],
 ['   45 | DEREK YAN                       |3.0  |L   5|L  51|D  60|L  56|W  63|D  55|W  58|'],
 ['   46 | JACOB ALEXANDER LAVALLEY        |3.0  |W  35|L   7|L  27|L  50|W  64|W  43|L  23|'],
 ['   47 | ERIC WRIGHT                     |2.5  |L  18|W  24|L  21|W  61|L   8|D  51|L  25|'],
 ['   48 | DANIEL KHAIN                    |2.5  |L  17|W  63|H    |D  52|H    |L  29|L  35|'],
 ['   49 | MICHAEL J MARTIN                |2.5  |L  26|L  20|D  63|D  64|W  58|H    |U    |'],
 ['   50 | SHIVAM JHA                      |2.5  |L  29|W  42|L  33|W  46|H    |L  31|L  30|'],
 ['   51 | TEJAS AYYAGARI                  |2.5  |L  27|W  45|L  36|W  57|L  32|D  47|L  33|'],
 ['   52 | ETHAN GUO                       |2.5  |W  30|D  22|L  19|D  48|L  29|D  35|L  34|'],
 ['   53 | JOSE C YBARRA                   |2.0  |H    |L  25|H    |L  44|U    |W  57|U    |'],
 ['   54 | LARRY HODGE                     |2.0  |L  14|L  39|L  61|B    |L  15|L  59|W  64|'],
 ['   55 | ALEX KONG                       |2.0  |L  62|D  31|L  10|L  30|B    |D  45|L  43|'],
 ['   56 | MARISA RICCI                    |2.0  |H    |L  11|L  35|W  45|H    |L  40|L  42|'],
 ['   57 | MICHAEL LU                      |2.0  |L   7|L  36|W  42|L  51|L  35|L  53|B    |'],
 ['   58 | VIRAJ MOHILE                    |2.0  |W  31|L   2|L  41|L  23|L  49|B    |L  45|'],
 ['   59 | SEAN M MC CORMICK               |2.0  |L  41|B    |L   9|L  40|L  43|W  54|L  44|'],
 ['   60 | JULIA SHEN                      |1.5  |L  33|L  34|D  45|D  42|L  24|H    |U    |'],
 ['   61 | JEZZEL FARKAS                   |1.5  |L  32|L   3|W  54|L  47|D  42|L  30|L  37|'],
 ['   62 | ASHWIN BALAJI                   |1.0  |W  55|U    |U    |U    |U    |U    |U    |'],
 ['   63 | THOMAS JOSEPH HOSMER            |1.0  |L   2|L  48|D  49|L  43|L  45|H    |U    |'],
 ['   64 | BEN LI                          |1.0  |L  22|D  30|L  31|D  49|L  46|L  42|L  54|']]

After getting player only data, we can use similar algorithm to get location and rating data.

In [19]:

#Similar algorithm and revised for this 

#using np arange to make spaced value. In this case, since we know the stop number of the line is 196.
row_num = np.arange(2,196,3)
step = 0
#create an empty loc_rating list
loc_rating = []

#using for loop to get loc_rating data
for i in my_list:
    if(step in row_num):
        loc_rating.append(i)
    step = step+1
#get loc_rating data
loc_rating

#Since there is no pair number ,using length funcion to check whether there is missing value or not.

[[' Num  | USCF ID / Rtg (Pre->Post)       | Pts |  1  |  2  |  3  |  4  |  5  |  6  |  7  | '],
 ['   ON | 15445895 / R: 1794   ->1817     |N:2  |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 14598900 / R: 1553   ->1663     |N:2  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 14959604 / R: 1384   ->1640     |N:2  |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 12616049 / R: 1716   ->1744     |N:2  |W    |B    |W    |B    |W    |B    |B    |'],
 ['   MI | 14601533 / R: 1655   ->1690     |N:2  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   OH | 15055204 / R: 1686   ->1687     |N:3  |W    |B    |W    |B    |B    |W    |B    |'],
 ['   MI | 11146376 / R: 1649   ->1673     |N:3  |W    |B    |W    |B    |B    |W    |W    |'],
 ['   MI | 15142253 / R: 1641P17->1657P24  |N:3  |B    |W    |B    |W    |B    |W    |W    |'],
 ['   ON | 14954524 / R: 1411   ->1564     |N:2  |W    |B    |W    |B    |W    |B    |B    |'],
 ['   MI | 14150362 / R: 1365   ->1544     |N:3  |W    |W    |B    |B    |W    |B    |W    |'],
 ['   MI | 12581589 / R: 1712   ->1696     |N:3  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 12681257 / R: 1663   ->1670     |N:3  |W    |B    |W    |B    |     |W    |B    |'],
 ['   MI | 15082995 / R: 1666   ->1662     |N:3  |B    |W    |B    |B    |W    |W    |B    |'],
 ['   MI | 10131499 / R: 1610   ->1618     |N:3  |W    |B    |W    |W    |B    |B    |W    |'],
 ['   MI | 15619130 / R: 1220P13->1416P20  |N:3  |B    |B    |W    |W    |B    |B    |W    |'],
 ['   MI | 10295068 / R: 1604   ->1613     |N:3  |B    |W    |     |B    |W    |B    |     |'],
 ['   MI | 10297702 / R: 1629   ->1610     |N:3  |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 11342094 / R: 1600   ->1600     |N:3  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 14862333 / R: 1564   ->1570     |N:3  |W    |B    |W    |B    |W    |W    |B    |'],
 ['   MI | 14529060 / R: 1595   ->1569     |N:4  |W    |B    |W    |B    |W    |B    |W    |'],
 ['   ON | 15495066 / R: 1563P22->1562     |N:3  |B    |W    |B    |W    |W    |B    |W    |'],
 ['   MI | 12405534 / R: 1555   ->1529     |N:4  |W    |B    |W    |B    |     |W    |B    |'],
 ['   ON | 15030142 / R: 1363   ->1371     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 13469010 / R: 1229   ->1300     |N:4  |B    |W    |B    |B    |W    |W    |B    |'],
 ['   MI | 12486656 / R: 1745   ->1681     |N:4  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   ON | 15131520 / R: 1579   ->1564     |N:4  |B    |W    |B    |W    |B    |W    |W    |'],
 ['   MI | 14476567 / R: 1552   ->1539     |N:4  |W    |B    |W    |B    |W    |B    |     |'],
 ['   MI | 14882954 / R: 1507   ->1513     |N:3  |W    |W    |B    |W    |B    |B    |W    |'],
 ['   MI | 15323285 / R: 1602P6 ->1508P12  |N:4  |B    |W    |B    |W    |W    |B    |     |'],
 ['   ON | 12577178 / R: 1522   ->1444     |     |W    |B    |B    |W    |W    |B    |B    |'],
 ['   MI | 15131618 / R: 1494   ->1444     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['   ON | 14073750 / R: 1441   ->1433     |N:4  |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 14691842 / R: 1449   ->1421     |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 15051807 / R: 1399   ->1400     |     |B    |W    |B    |B    |W    |B    |W    |'],
 ['   MI | 14601397 / R: 1438   ->1392     |     |W    |W    |B    |W    |B    |B    |W    |'],
 ['   MI | 14773163 / R: 1355   ->1367     |N:4  |W    |B    |W    |B    |     |W    |B    |'],
 ['   MI | 15489571 / R:  980P12->1077P17  |     |     |B    |W    |W    |     |B    |W    |'],
 ['   MI | 15108523 / R: 1423   ->1439     |N:4  |W    |B    |W    |W    |     |B    |B    |'],
 ['   MI | 12923035 / R: 1436P23->1413     |N:4  |B    |W    |B    |W    |B    |W    |W    |'],
 ['   MI | 14892710 / R: 1348   ->1346     |     |B    |B    |W    |W    |B    |W    |W    |'],
 ['   MI | 15761443 / R: 1403P5 ->1341P9   |     |B    |W    |B    |W    |     |     |     |'],
 ['   MI | 14462326 / R: 1332   ->1256     |     |B    |W    |B    |B    |W    |W    |B    |'],
 ['   MI | 14101068 / R: 1283   ->1244     |     |W    |B    |W    |W    |B    |B    |W    |'],
 ['   MI | 15323504 / R: 1199   ->1199     |     |     |W    |B    |B    |W    |B    |W    |'],
 ['   MI | 15372807 / R: 1242   ->1191     |     |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 15490981 / R:  377P3 ->1076P10  |     |B    |W    |B    |W    |B    |W    |W    |'],
 ['   MI | 12533115 / R: 1362   ->1341     |     |W    |B    |W    |B    |W    |B    |W    |'],
 ['   MI | 14369165 / R: 1382   ->1335     |     |B    |W    |     |B    |     |W    |B    |'],
 ['   MI | 12531685 / R: 1291P12->1259P17  |     |W    |W    |B    |W    |B    |     |     |'],
 ['   MI | 14773178 / R: 1056   ->1111     |     |W    |B    |W    |B    |     |B    |W    |'],
 ['   MI | 15205474 / R: 1011   ->1097     |     |B    |W    |B    |W    |B    |W    |W    |'],
 ['   MI | 14918803 / R:  935   ->1092     |N:4  |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 12578849 / R: 1393   ->1359     |     |     |B    |     |W    |     |W    |     |'],
 ['   MI | 12836773 / R: 1270   ->1200     |     |B    |B    |W    |     |W    |B    |W    |'],
 ['   MI | 15412571 / R: 1186   ->1163     |     |W    |B    |W    |B    |     |W    |B    |'],
 ['   MI | 14679887 / R: 1153   ->1140     |     |     |B    |W    |W    |     |B    |W    |'],
 ['   MI | 15113330 / R: 1092   ->1079     |     |B    |W    |W    |B    |W    |B    |     |'],
 ['   MI | 14700365 / R:  917   -> 941     |     |W    |B    |W    |B    |W    |     |B    |'],
 ['   MI | 12841036 / R:  853   -> 878     |     |W    |     |B    |B    |W    |W    |B    |'],
 ['   MI | 14579262 / R:  967   -> 984     |     |W    |B    |B    |W    |B    |     |     |'],
 ['   ON | 15771592 / R:  955P11-> 979P18  |     |B    |W    |B    |W    |B    |W    |B    |'],
 ['   MI | 15219542 / R: 1530   ->1535     |     |B    |     |     |     |     |     |     |'],
 ['   MI | 15057092 / R: 1175   ->1125     |     |W    |B    |W    |B    |B    |     |     |'],
 ['   MI | 15006561 / R: 1163   ->1112     |     |B    |W    |W    |B    |W    |B    |B    |']]

After getting these two list values, regular expression can be used to find names,rating,state and points. 
Firstly, I start with the name of regular expression

In [20]:
# create a regex for name
name_re = re.compile("[A-Za-z]+\s[A-Za-z]+")
# use findall function to find all names
name = name_re.findall(str(player_only))
#print name
name

['Player Name',
 'GARY HUA',
 'DAKSHESH DARURI',
 'ADITYA BAJAJ',
 'PATRICK H',
 'HANSHI ZUO',
 'HANSEN SONG',
 'GARY DEE',
 'EZEKIEL HOUGHTON',
 'STEFANO LEE',
 'ANVIT RAO',
 'CAMERON WILLIAM',
 'MC LEMAN',
 'KENNETH J',
 'TORRANCE HENRY',
 'BRADLEY SHAW',
 'ZACHARY JAMES',
 'MIKE NIKITIN',
 'RONALD GRZEGORCZYK',
 'DAVID SUNDEEN',
 'DIPANKAR ROY',
 'JASON ZHENG',
 'DINH DANG',
 'EUGENE L',
 'ALAN BUI',
 'MICHAEL R',
 'LOREN SCHWIEBERT',
 'MAX ZHU',
 'GAURAV GIDWANI',
 'SOFIA ADINA',
 'CHIEDOZIE OKORIE',
 'GEORGE AVERY',
 'RISHI SHETTY',
 'JOSHUA PHILIP',
 'JADE GE',
 'MICHAEL JEFFERY',
 'JOSHUA DAVID',
 'SIDDHARTH JHA',
 'AMIYATOSH PWNANANDAM',
 'BRIAN LIU',
 'JOEL R',
 'FOREST ZHANG',
 'KYLE WILLIAM',
 'JARED GE',
 'ROBERT GLEN',
 'JUSTIN D',
 'DEREK YAN',
 'JACOB ALEXANDER',
 'ERIC WRIGHT',
 'DANIEL KHAIN',
 'MICHAEL J',
 'SHIVAM JHA',
 'TEJAS AYYAGARI',
 'ETHAN GUO',
 'JOSE C',
 'LARRY HODGE',
 'ALEX KONG',
 'MARISA RICCI',
 'MICHAEL LU',
 'VIRAJ MOHILE',
 'SEAN M',
 'MC CORMICK',
 'JULIA SHEN',
 'JEZZEL FARKAS',
 'ASHWIN BALAJI',
 'THOMAS JOSEPH',
 'BEN LI']

It is noticeable Player Name is also in this name list. One more step need to take to remove it.

In [21]:
#remove strings from name list 
name.remove('Player Name')
name

['GARY HUA',
 'DAKSHESH DARURI',
 'ADITYA BAJAJ',
 'PATRICK H',
 'HANSHI ZUO',
 'HANSEN SONG',
 'GARY DEE',
 'EZEKIEL HOUGHTON',
 'STEFANO LEE',
 'ANVIT RAO',
 'CAMERON WILLIAM',
 'MC LEMAN',
 'KENNETH J',
 'TORRANCE HENRY',
 'BRADLEY SHAW',
 'ZACHARY JAMES',
 'MIKE NIKITIN',
 'RONALD GRZEGORCZYK',
 'DAVID SUNDEEN',
 'DIPANKAR ROY',
 'JASON ZHENG',
 'DINH DANG',
 'EUGENE L',
 'ALAN BUI',
 'MICHAEL R',
 'LOREN SCHWIEBERT',
 'MAX ZHU',
 'GAURAV GIDWANI',
 'SOFIA ADINA',
 'CHIEDOZIE OKORIE',
 'GEORGE AVERY',
 'RISHI SHETTY',
 'JOSHUA PHILIP',
 'JADE GE',
 'MICHAEL JEFFERY',
 'JOSHUA DAVID',
 'SIDDHARTH JHA',
 'AMIYATOSH PWNANANDAM',
 'BRIAN LIU',
 'JOEL R',
 'FOREST ZHANG',
 'KYLE WILLIAM',
 'JARED GE',
 'ROBERT GLEN',
 'JUSTIN D',
 'DEREK YAN',
 'JACOB ALEXANDER',
 'ERIC WRIGHT',
 'DANIEL KHAIN',
 'MICHAEL J',
 'SHIVAM JHA',
 'TEJAS AYYAGARI',
 'ETHAN GUO',
 'JOSE C',
 'LARRY HODGE',
 'ALEX KONG',
 'MARISA RICCI',
 'MICHAEL LU',
 'VIRAJ MOHILE',
 'SEAN M',
 'MC CORMICK',
 'JULIA SHEN',
 'JEZZEL FARKAS',
 'ASHWIN BALAJI',
 'THOMAS JOSEPH',
 'BEN LI']

Then we can create the total points data.

In [22]:
#Using similar method
# create a regex for total points
totalpt_re = re.compile("[0-9]\.[0-9]")
# use findall function to find all total points
totalpt= totalpt_re.findall(str(player_only))
#print totalpt
totalpt

['6.0',
 '6.0',
 '6.0',
 '5.5',
 '5.5',
 '5.0',
 '5.0',
 '5.0',
 '5.0',
 '5.0',
 '4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '4.0',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.5',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '3.0',
 '2.5',
 '2.5',
 '2.5',
 '2.5',
 '2.5',
 '2.5',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '2.0',
 '1.5',
 '1.5',
 '1.0',
 '1.0',
 '1.0']

Then using similar method to create the state data.

In [23]:
#Using similar method
# create a regex for state
state_re = re.compile("[A-Z]{2}")
# use findall function to find all state
state= state_re.findall(str(loc_rating))
#print state
state

['US',
 'CF',
 'ID',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'OH',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI']

Also, there is three more wrong strings(US,CF and ID) was found,since first state was supposed to be ON.

In [24]:
#remove three strings from list. 
#duplicate_state=('US','CF','ID') hard way of removing
state.remove('US')
state.remove('CF')
state.remove('ID')
state

['ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'OH',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'MI',
 'ON',
 'MI',
 'MI',
 'MI']

Then using similar method to create the pre tournament rating data.

In [25]:
#Using similar method
# create a regex for pre tournament rating add : to avoid also get post tournament value
prerating_re = re.compile("\:\s+[0-9]{3,4}")
# use findall function to find all state
prerating= prerating_re.findall(str(loc_rating))
#print state
prerating

[': 1794',
 ': 1553',
 ': 1384',
 ': 1716',
 ': 1655',
 ': 1686',
 ': 1649',
 ': 1641',
 ': 1411',
 ': 1365',
 ': 1712',
 ': 1663',
 ': 1666',
 ': 1610',
 ': 1220',
 ': 1604',
 ': 1629',
 ': 1600',
 ': 1564',
 ': 1595',
 ': 1563',
 ': 1555',
 ': 1363',
 ': 1229',
 ': 1745',
 ': 1579',
 ': 1552',
 ': 1507',
 ': 1602',
 ': 1522',
 ': 1494',
 ': 1441',
 ': 1449',
 ': 1399',
 ': 1438',
 ': 1355',
 ':  980',
 ': 1423',
 ': 1436',
 ': 1348',
 ': 1403',
 ': 1332',
 ': 1283',
 ': 1199',
 ': 1242',
 ':  377',
 ': 1362',
 ': 1382',
 ': 1291',
 ': 1056',
 ': 1011',
 ':  935',
 ': 1393',
 ': 1270',
 ': 1186',
 ': 1153',
 ': 1092',
 ':  917',
 ':  853',
 ':  967',
 ':  955',
 ': 1530',
 ': 1175',
 ': 1163']

Since it still has special character, another step need to take

In [26]:
#clean the data
cleanup_re = re.compile("[0-9]{3,4}")
# use findall function to find all state
pre_rating= cleanup_re.findall(str(prerating))
#print state
pre_rating

['1794',
 '1553',
 '1384',
 '1716',
 '1655',
 '1686',
 '1649',
 '1641',
 '1411',
 '1365',
 '1712',
 '1663',
 '1666',
 '1610',
 '1220',
 '1604',
 '1629',
 '1600',
 '1564',
 '1595',
 '1563',
 '1555',
 '1363',
 '1229',
 '1745',
 '1579',
 '1552',
 '1507',
 '1602',
 '1522',
 '1494',
 '1441',
 '1449',
 '1399',
 '1438',
 '1355',
 '980',
 '1423',
 '1436',
 '1348',
 '1403',
 '1332',
 '1283',
 '1199',
 '1242',
 '377',
 '1362',
 '1382',
 '1291',
 '1056',
 '1011',
 '935',
 '1393',
 '1270',
 '1186',
 '1153',
 '1092',
 '917',
 '853',
 '967',
 '955',
 '1530',
 '1175',
 '1163']

## Create Dataframe

In [27]:

table= {'Player Name':name,'Total Point':totalpt, 'State':state,'Pre_T_Rating':pre_rating} 
# Create DataFrame 
dataframe = pd.DataFrame(table) 
dataframe

ValueError: arrays must all be same length

Error comes from not the same length. 
may be caused by regex filter in name.

In [28]:
#For partial credits
table= {'Total Point':totalpt,'State':state,'Pre_T_Rating':pre_rating} 
# Create DataFrame and verfied error is in name.
dataframe = pd.DataFrame(table) 
print(dataframe)

   Total Point State Pre_T_Rating
0          6.0    ON         1794
1          6.0    MI         1553
2          6.0    MI         1384
3          5.5    MI         1716
4          5.5    MI         1655
5          5.0    OH         1686
6          5.0    MI         1649
7          5.0    MI         1641
8          5.0    ON         1411
9          5.0    MI         1365
10         4.5    MI         1712
11         4.5    MI         1663
12         4.5    MI         1666
13         4.5    MI         1610
14         4.5    MI         1220
15         4.0    MI         1604
16         4.0    MI         1629
17         4.0    MI         1600
18         4.0    MI         1564
19         4.0    MI         1595
20         4.0    ON         1563
21         4.0    MI         1555
22         4.0    ON         1363
23         4.0    MI         1229
24         3.5    MI         1745
25         3.5    ON         1579
26         3.5    MI         1552
27         3.5    MI         1507
28         3.5    MI         1602
29         3.5    ON         1522
..         ...   ...          ...
34         3.5    MI         1438
35         3.5    MI         1355
36         3.5    MI          980
37         3.0    MI         1423
38         3.0    MI         1436
39         3.0    MI         1348
40         3.0    MI         1403
41         3.0    MI         1332
42         3.0    MI         1283
43         3.0    MI         1199
44         3.0    MI         1242
45         3.0    MI          377
46         2.5    MI         1362
47         2.5    MI         1382
48         2.5    MI         1291
49         2.5    MI         1056
50         2.5    MI         1011
51         2.5    MI          935
52         2.0    MI         1393
53         2.0    MI         1270
54         2.0    MI         1186
55         2.0    MI         1153
56         2.0    MI         1092
57         2.0    MI          917
58         2.0    MI          853
59         1.5    MI          967
60         1.5    ON          955
61         1.0    MI         1530
62         1.0    MI         1175
63         1.0    MI         1163

[64 rows x 3 columns]

#### Export Data to csv file

In [29]:
#export to csv file
dataframe.to_csv("tournament.csv",index=0)

## Insights for future steps

Due to timing manner, I did not have time to continue the latter process, there are some of my insights for what to do next.
Similar to the excel vloopkup function, the pair number of each player is like an index. Since average pre chessing rating of opponent 's score is only based on average pre rating score of 7 rounds. From previous two part, we already know each player's pre rating score. Firstly 
we can use loc function to find corresonding value of opponent based on round. In order to process loc function. Future Step should be completed based on the Data Frame.